//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Admin
    {
       [Required (ErrorMessage ="this fiel is required to continue")]
        public int id { get; set; }


        [Required(ErrorMessage = "this fiel is required to continue")]
        public string name { get; set; }


        [Required(ErrorMessage = "this fiel is required to continue")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }


        [Required(ErrorMessage = "this fiel is required to continue")]
        [DataType(DataType.Password)]
        public string password { get; set; }


        [Required(ErrorMessage = "this fiel is required to continue")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> contact { get; set; }
    }
}
