//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Novel
    {
        [Required(ErrorMessage = "this fiel is required to continue")]
        public int id { get; set; }

        [Required(ErrorMessage = "this fiel is required to continue")]
        public string bookName { get; set; }

        [Required(ErrorMessage = "this fiel is required to continue")]
        public string Author { get; set; }

        [Required(ErrorMessage = "this fiel is required to continue")]
        public string Description { get; set; }
    }
}
